name: CI
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'src/v**'
      - 'v**'
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Installing jsonnet and jsonnet-bundler
      run: |
        go get github.com/google/go-jsonnet/cmd/jsonnet
        go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: make deps

    - name: Test
      run: make test-frontend-coverage test-backend-coverage

    - name: End-to-End tests
      run: make test-e2e

    - name: Build
      run: make dist

    - name: Publish build artifact
      uses: actions/upload-artifact@v2
      with:
        name: grafana-pcp
        path: dist
