name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Installing jsonnet and jsonnet-bundler
      run: |
        go get github.com/google/go-jsonnet/cmd/jsonnet
        go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: make deps

    - name: Build plugin
      run: make dist

    #- name: Sign plugin
    #  run: make sign
    #  env:
    #    GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}

    - name: Create GitHub release
      run: scripts/github-release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
